### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by marmarek** [redspider/pybear#4]
The library doesn't have defined license - as is [it isn't legal to use or distribute it anywhere without explicit permission](https://choosealicense.com/no-permission/#for-users) from the authors (effectively asking for explicit license each time). 
It is obviously up to the code authors (copyright holders) to decide, but I would recommend either LGPL-2+ or MIT (see also https://choosealicense.com/).
Fortunately at this stage there are just three authors: @redspider @rootkovska @woju , so I hope it won't be a problem to agree on some.

**Comment by rootkovska** [comment]
Any is fine for me 👍 
@redspider? :)

**Comment by redspider** [comment]
I am fine with the use of the MIT license for my code / for the project as a whole. I would accept a pull request with that license in place.
